apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: jenkins-test-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    app.kubernetes.io/part-of: jenkins-test-app
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  - name: testing_pipeline_matching_labels
    value:
      apps.tanzu.vmware.com/pipeline: jenkins-pipeline
      apps.tanzu.vmware.com/language: java
  - name: testing_pipeline_params
    value:
      job-name: tanzu-java-web--app
      secret-name: jenkins-secret
      #job-params: [{name:GIT_URL, value:https://github.com/stuartblackburnvmware/jenkins-test-app}, {name:GIT_BRANCH, value:main}]
      job-params: "[{\"name\":\"GIT_URL\", \"value\":\"https://github.com/stuartblackburnvmware/jenkins-test-app\"}, {\"name\":\"GIT_BRANCH\", \"value\":\"main\"}]"
      #job-params: "[{\"name\":\"A\",\"value\":\"x\"},{\"name\":\"B\",\"value\":\"y\"},...]"
  source:
    git:
      url: https://github.com/stuartblackburnvmware/jenkins-test-app
      ref:
        branch: main
